name: movie_app
description: "Movie App Flutter Project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  bloc: ^9.0.0
  auto_route: ^10.1.0+1
  dartz: ^0.10.1
  equatable: ^2.0.7
  flex_color_scheme: ^8.2.0
  flutter_adaptive_scaffold: ^0.3.3+1
  freezed_annotation: ^3.1.0
  freezed: ^3.1.0
  dio: ^5.8.0+1
  injectable: ^2.5.1
  retrofit: ^4.6.0
  json_annotation: ^4.9.0
  flutter_bloc: ^9.1.1
  get_it: ^8.2.0
  flutter_dotenv: ^5.2.1
  carousel_slider: ^5.1.1
  intl: ^0.20.2
  flutter_typeahead: ^5.2.0
  shared_preferences: ^2.5.3
  shimmer: ^3.0.0
  hive: ^2.2.3
  path_provider: ^2.1.5
  hive_flutter: ^1.1.0
  cached_network_image: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  auto_route_generator: ^10.0.1
  build_runner: ^2.4.15
  json_serializable: ^6.9.4
  retrofit_generator: ^9.7.0
  injectable_generator: ^2.6.2
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.6

#  hive_generator: ^2.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/movies_logo.png"

flutter_native_splash:
  color: "#ffffff"
  image: "assets/images/movies_logo.png"
  android: true
  ios: true

flutter:
    uses-material-design: true
    generate: true
    assets:
      - assets/
      - assets/fonts/
      - .env
      - assets/images/
      - assets/data/
    fonts:
      - family: OpenSans
        fonts:
          - asset: assets/fonts/OpenSans-Italic-VariableFont_wdth,wght.ttf
          - asset: assets/fonts/OpenSans-VariableFont_wdth,wght.ttf
